name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
          check-latest: false
          cache: 'gradle'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image   
        run:
         export BP_JVM_TYPE=JDK && ./gradlew --no-daemon --max-workers 1 bootBuildImage --imageName docker.io/strehle/uaa:${{ github.run_number }} --publishImage
#         ./gradlew --no-daemon --max-workers 1 bootBuildImage --imageName docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.run_number }} --publishImage
#      - name: Build the Docker image
#        run:  >-
#          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} &&
#          ./gradlew --no-daemon --max-workers 1 bootBuildImage --imageName ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.run_number }} --publishImage
#      - name: Tag image
#        run: docker tag strehle/${{ github.repository }}:${{ github.run_number }} strehle/${{ github.repository }}:latest
#      - name: Push Docker image
#        if: ${{ github.event_name != 'pull_request' }}
#        run: >-
#          docker push strehle/${{ github.repository }}:${{ github.run_number }}
#          docker push strehle/${{ github.repository }}:latest &&
